### ISSUE TITLE
Dark theme can go out of sync with setting in Firefox

### ISSUE THREAD

**Issue by Schnark** [freeCodeCamp/devdocs#613]
Steps to reproduce:
1. Use Firefox
2. Go to http://devdocs.io/settings
3. Select "Enable dark theme".
4. Reload page.

-> "Enable dark theme" is checked, but the light theme is shown. Toggling the checkbox toggles the theme, but is out of sync.

I can't reproduce this perfectly reliable (especially I can't reproduce in a private window), but even if the bug doesn't show the first time, just keep reloading and checking/unchecking the checkbox, and sooner or later the bug will show up. This can also happen without direct reload by opening the settings while offline.

This is probably caused by the strange behaviour in Firefox to persist the checked state across reloads, and so can probably be fixed by setting the `autocomplete` attribute to `off`, see http://devdocs.io/html/element/input.

**Comment by jonian** [comment]
Hi I have the same issue using [epiphany](https://wiki.gnome.org/Apps/Web/) web browser and [devdocs-desktop](https://github.com/hardpixel/devdocs-desktop) app.

Both apps use [webkit2gtk](https://webkitgtk.org) engine.

In my case reproducing it is more consistent:

1. Select "Enable dark theme".
2. Reload page.

"Enable dark theme" is checked, but the light theme is shown. Toggling the checkbox toggles the theme, but is out of sync.

**Comment by Thibaut** [comment]
This is likely happening because the application cache needs to be updated/downloaded (by the browser) before reloading the page, which takes a few seconds, or the browser will reload the page using the old cache, which will activate the previous (wrong) color scheme. The setting is persisted correctly, just the cache doesn't keep up. If you re-reload after a few seconds, you should see the right color scheme.

I think this issue is a bit of an edge case, but will try to fix it when I have time.

**Comment by noxecane** [comment]
Same here with chrome. I enabled the dark theme. But later disabled it(I'm not sure whether I was connected to the internet when I disabled it). When I reloaded it while offline, it was using the dark theme as described. Perhaps I could help fix it

**Comment by ajitid** [comment]
It is fixed in Firefox Quantum

**Comment by Thibaut** [comment]
This should be fixed now that we've switched the app to using CSS variables instead of a separate stylesheet for the dark mode. #858.

**Comment by Kidcredo** [comment]
I still have this issue and i am using Firefox Developer Edition 67.0b2
